### ISSUE TITLE
Can we contribute to this project?

### ISSUE THREAD

**Issue by paulbares** [coralblocks/CoralRing#1]
Hi there, 

I was wondering if I can open pull requests for this project. I can't see any contributing guidelines, code of conduct...

**Comment by coralblocks** [comment]
Hi Paul,

Thanks for reaching out. You are welcome to contribute. We have included the [CLA.md](https://github.com/coralblocks/CoralRing/blob/main/CLA.md) and the [CONTRIBUTIONS.md](https://github.com/coralblocks/CoralRing/blob/main/CONTRIBUTING.md) files in the repository. What contribution did you have in mind?

**Comment by paulbares** [comment]
Just fixing a few of typos in the README and the javadoc for the time being :nerd_face:
